Operation_Type = (('OPERATION_TYPE_UNSPECIFIED', 'Тип операции не определён'),
                  ('OPERATION_TYPE_INPUT', 'Пополнение брокерского счёта'),
                  ('OPERATION_TYPE_BOND_TAX', 'Удержание НДФЛ по купонам'),
                  ('OPERATION_TYPE_OUTPUT_SECURITIES', 'Вывод ЦБ'),
                  ('OPERATION_TYPE_OVERNIGHT', 'Доход по сделке РЕПО овернайт'),
                  ('OPERATION_TYPE_TAX', 'Удержание налога'),
                  ('OPERATION_TYPE_BOND_REPAYMENT_FULL', 'Полное погашение облигаций'),
                  ('OPERATION_TYPE_SELL_CARD', 'Продажа ЦБ с карты'),
                  ('OPERATION_TYPE_DIVIDEND_TAX', 'Удержание налога по дивидендам'),
                  ('OPERATION_TYPE_OUTPUT', 'Вывод денежных средств'),
                  ('OPERATION_TYPE_BOND_REPAYMENT', 'Частичное погашение облигаций'),
                  ('OPERATION_TYPE_TAX_CORRECTION', 'Корректировка налога'),
                  ('OPERATION_TYPE_SERVICE_FEE', 'Удержание комиссии за обслуживание брокерского счёта'),
                  ('OPERATION_TYPE_BENEFIT_TAX', 'Удержание налога за материальную выгоду'),
                  ('OPERATION_TYPE_MARGIN_FEE', 'Удержание комиссии за непокрытую позицию'),
                  ('OPERATION_TYPE_BUY', 'Покупка ЦБ'),
                  ('OPERATION_TYPE_BUY_CARD', 'Покупка ЦБ с карты'),
                  ('OPERATION_TYPE_INPUT_SECURITIES', 'Перевод ценных бумаг из другого депозитария'),
                  ('OPERATION_TYPE_SELL_MARGIN', 'Продажа в результате Margin-call'),
                  ('OPERATION_TYPE_BROKER_FEE', 'Удержание комиссии за операцию'),
                  ('OPERATION_TYPE_BUY_MARGIN', 'Покупка в результате Margin-call'),
                  ('OPERATION_TYPE_DIVIDEND', 'Выплата дивидендов'),
                  ('OPERATION_TYPE_SELL', 'Продажа ЦБ'),
                  ('OPERATION_TYPE_COUPON', 'Выплата купонов'),
                  ('OPERATION_TYPE_SUCCESS_FEE', 'Удержание комиссии SuccessFee'),
                  ('OPERATION_TYPE_DIVIDEND_TRANSFER', 'Передача дивидендного дохода'),
                  ('OPERATION_TYPE_ACCRUING_VARMARGIN', 'Зачисление вариационной маржи'),
                  ('OPERATION_TYPE_WRITING_OFF_VARMARGIN', 'Списание вариационной маржи'),
                  ('OPERATION_TYPE_DELIVERY_BUY', 'Покупка в рамках экспирации фьючерсного контракта'),
                  ('OPERATION_TYPE_DELIVERY_SELL', 'Продажа в рамках экспирации фьючерсного контракта'),
                  ('OPERATION_TYPE_TRACK_MFEE', 'Комиссия за управление по счёту автоследования'),
                  ('OPERATION_TYPE_TRACK_PFEE', 'Комиссия за результат по счёту автоследования'),
                  ('OPERATION_TYPE_TAX_PROGRESSIVE', 'Удержание налога по ставке 15%'),
                  ('OPERATION_TYPE_BOND_TAX_PROGRESSIVE', 'Удержание налога по купонам по ставке 15%'),
                  ('OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE', '	Удержание налога по дивидендам по ставке 15%'),
                  ('OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE', 'Удержание налога за материальную выгоду по ставке 15%'),
                  ('OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE', 'Корректировка налога по ставке 15%'),
                  ('OPERATION_TYPE_TAX_REPO_PROGRESSIVE', 'Удержание налога за возмещение по сделкам РЕПО по ставке 15%'),
                  ('OPERATION_TYPE_TAX_REPO', 'Удержание налога за возмещение по сделкам РЕПО'),
                  ('OPERATION_TYPE_TAX_REPO_HOLD', 'Удержание налога по сделкам РЕПО'),
                  ('OPERATION_TYPE_TAX_REPO_REFUND', 'Возврат налога по сделкам РЕПО'),
                  ('OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE', 'Удержание налога по сделкам РЕПО по ставке 15%'),
                  ('OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE', 'Возврат налога по сделкам РЕПО по ставке 15%'),
                  ('OPERATION_TYPE_DIV_EXT', 'Выплата дивидендов на карту'),
                  ('OPERATION_TYPE_TAX_CORRECTION_COUPON', 'Корректировка налога по купонам'))
